### PR TITLE
Added sequence spawner to fix #133

### LINKED ISSUE #133: Spawn Random Sequences
We need to set up a benchmark testing regime. To accomplish this, we could commit some large demo files to the repo, but this is undesirable (as the repo and dependencies are already huge, relative to the size of the app). Instead, we could write a [sequence spawner](https://github.com/CDCgov/SeqSpawnR) directly into the application itself. We don't need any UI for it, just a function that could generate them and ingest them as though they were being parsed from a file(s).

### PR DESCRIPTION
**Pull request by gmkarl**
Usage in development console:
```app.addFile(new File([app.unparseFASTA(app.generateSeqs("gen-", 50, 20))], "generated.fasta"))```

#133

### CODE REVIEW

**Comment by AABoyles** [comment]
This is SO COOL! Thanks for tackling this project! One tiny modification requested: [that seed string](https://github.com/CDCgov/MicrobeTrace/pull/139/files#diff-a31a904ec70b545ac9c417826ca193b7R287) is already available in [`app.dataSkeleton().reference`](https://github.com/CDCgov/MicrobeTrace/blob/master/scripts/common.js#L14). Moreover, it makes sense to me to simply default to the session reference string (`session.data.reference`), instead of hard-coding one in like this.

**Comment by gmkarl** [comment]
@AABoyles, I implemented your requested change.

After reading your response on https://github.com/CDCgov/SeqSpawnR/issues/1, I also tried to tweak the algorithm so as to _always_ do codon replacement, but because this seems likely to me to change statistical properties a little, this change is on a separate branch at 
https://github.com/gmkarl/MicrobeTrace/compare/seqgen...gmkarl:seqgen-tweak.  The untweaked algorithm looks to me like it will skip codon replacement increasingly as it works with increasingly mutated seeds.

I'm not sure how to actually measure the statistical properties of genetic sequences, or I would have only presented the right solution =)

**Comment by AABoyles** [comment]
Thanks @gmkarl! Sorry, I should've been a little more explicit than just saying "statistical properties." The only thing I really care about is that the pairwise genetic distances across the entire matrix are normally distributed. You can confirm this by loading up your random sequences in MicrobeTrace, launching the network, and then clicking settings. The settings modal has a small black histogram in it. If that histogram shows a normal curve, we're good. I'll test it right now.

**Comment by AABoyles** [comment]
...And it looks great! Thanks again, @gmkarl!

**Pull request merged**
